### ISSUE TITLE
hfss design

### ISSUE THREAD

**Issue by abhishekgoulla** [amartya-singh/1X2-Circular-Patch-Array-Antenna-using-HFSS#1]
hello!
will you share a rectangular patch antenna array with ebg structure?
or share the design calculation for rectangular patch array design.

**Comment by amartya-singh** [comment]
Hi,
The calculation has already been shown in the .pdf file.
I hope it will help you.

Regarding ebg structure: 
Now I had left designing antennas and now I am working as a firmware engineer. So, now I do not have the software installed to design neither the skill and knowledge related to designing an antenna. So, sorry about that.

**Comment by abhishekgoulla** [comment]
oh, Thank you.
